version: "3"

services:
  hid:
    build:
      context: .
      privileged: true
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/dbus:/var/run/dbus
    tty: true
    stdin_open: true
